// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7gBTOVmG-Jeg15uDTjQ1P4dftgDktSdI',
    appId: '1:1031259736492:web:c969f0d86132f37401d209',
    messagingSenderId: '1031259736492',
    projectId: 'animetracker-227be',
    authDomain: 'animetracker-227be.firebaseapp.com',
    storageBucket: 'animetracker-227be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS6W0wlVggFkDpcmMatQnYgyhzIK7mpnU',
    appId: '1:1031259736492:android:df005dbb4e67b6e701d209',
    messagingSenderId: '1031259736492',
    projectId: 'animetracker-227be',
    storageBucket: 'animetracker-227be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq8-Y1QPVQJNbHm83gFd0pIQtlScpJeV0',
    appId: '1:1031259736492:ios:14e598b9eeabeade01d209',
    messagingSenderId: '1031259736492',
    projectId: 'animetracker-227be',
    storageBucket: 'animetracker-227be.firebasestorage.app',
    iosBundleId: 'com.example.animeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq8-Y1QPVQJNbHm83gFd0pIQtlScpJeV0',
    appId: '1:1031259736492:ios:14e598b9eeabeade01d209',
    messagingSenderId: '1031259736492',
    projectId: 'animetracker-227be',
    storageBucket: 'animetracker-227be.firebasestorage.app',
    iosBundleId: 'com.example.animeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7gBTOVmG-Jeg15uDTjQ1P4dftgDktSdI',
    appId: '1:1031259736492:web:6c44c781407bf11801d209',
    messagingSenderId: '1031259736492',
    projectId: 'animetracker-227be',
    authDomain: 'animetracker-227be.firebaseapp.com',
    storageBucket: 'animetracker-227be.firebasestorage.app',
  );
}
